# Generated by Django 6.1 on 2026-09-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_teammember_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default='Main Background Video', max_length=255)),
                ('video_url', models.URLField(max_length=500)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('mux_asset_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mux_playback_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Background Video',
                'verbose_name_plural': 'Background Videos',
                'ordering': ['-updated_at'],
            },
        ),
    ]
